import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProviderComponent  } from "@/components/context/ThemeProvider";

const font = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Roicomsat Press",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={font.className}>
        <ThemeProviderComponent
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ModalProvider> */}
            {children}
            {/* <Toaster /> */}
            {/* <SonnarToaster position="bottom-left" /> */}
          {/* </ModalProvider> */}
        </ThemeProviderComponent>
      </body>
    </html>
  )
}
